name: Output Event Detail

on: issues

jobs:
  echo_event_details:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Echo Issue Event Details
        run: echo "Issuee ${{toJson(github.event.issue)}}"
